# Generated by Django 4.1.2 on 2022-10-12 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='images/%y/%m/%d')),
                ('content', models.TextField(max_length=1000)),
                ('published_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
